### ISSUE TITLE
Install SMV on local computer

### ISSUE THREAD

**Issue by misswhy** [misswhy/Hello-New-World#2]
Try 2 ways: 
1. JDK->Maven->Spark->SMV
2. Docker->SMV

**Comment by misswhy** [comment]
Install JDK 1.8 done. Current Java version on local machine: 1.8.0_101

**Comment by misswhy** [comment]
Install Maven done. Current Maven version: Apache Maven 3.3.9

**Comment by misswhy** [comment]
Install Scala done. Current Scala version: 2.10.4

**Comment by misswhy** [comment]
Install "happy version" Spark done. 
I first tried "thorough version" (build SPARK from source code), while meet an error: Unable to locate an executable at "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/javac". When I further check this directory, there's only java under /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/, but no javac. I guess this is the reason why build failed. But I didn't dig further on how to install javac on my computer, and switch to "happy version".

**Comment by misswhy** [comment]
I met the same error when trying to install smv... It seems javac is a must -- not sure which step went wrong that it did not installed. I'm going to re-install JDK and see.

**Comment by misswhy** [comment]
Install SMV done, issue solved.
The issue above was because I set up a wrong JAVA_HOME before. So here comes the question: how can I find the right path of JAVA_HOME after I installed JDK? Previously, I went to "system preference" page, click "JAVA", then a JAVA control panel was opened. I then went to "Java" tab and clicked view to see details, it is said the path was "/Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java" so I copied it to JAVA_HOME in my environment file. While it turns out the real JAVA_HOME should be "/Library/Java/JavaVirtualMachines/jdk1.8.0_101.jdk/Contents/Home", which I found by accident. Is there a way to know it quickly where JDK is installed?

**Comment by ninjapapa** [comment]
Not so sure. Is there answers on stackoverflow when you ask "how to find JAVA Home".

**Comment by misswhy** [comment]
Find it! 
There's a shell command: "/usr/libexec/java_home -V" to list all the installed JAVA version and its home folder. In case someone wants to have multiple JAVA version installed and used for different apps. Below settings in ~/.bashrc file may help:
alias java6="export JAVA_HOME=$(/usr/libexec/java_home -v 1.6);echo 'using Java 6'"
alias java8="export JAVA_HOME=$(/usr/libexec/java_home -v 1.8);echo 'using Java 8'"
